[browser]
gatherUsageStats = false

[server]
headless = true
address = "localhost"
port = 8501

[theme]
primaryColor = "#7C3AED"
backgroundColor = "#0F172A"
secondaryBackgroundColor = "#1E293B"
textColor = "#E2E8F0"
font = "sans serif"
